# Generated by Django 5.2.17 on 2026-09-23 10:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "subscription_category",
                    models.CharField(
                        choices=[("ice", "ICE"), ("hall", "HALL")], max_length=16
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GroupMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="group_memberships",
                        to="accounts.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("minimum_attendees", models.PositiveSmallIntegerField()),
                ("rsvp_deadline", models.DateTimeField()),
                ("decision_deadline", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("rsvp_open", "RSVP open"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("decision_evaluated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decision_yes_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "decision_no_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "decision_no_response_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attendance_submitted_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancellation_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low_attendance", "Low attendance"),
                            ("coach_unavailable", "Coach unavailable"),
                            ("venue_unavailable", "Venue unavailable"),
                            ("administrative", "Administrative"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "attendance_submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lessons",
                        to="accounts.coachprofile",
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "replacement_lesson",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replaced_lesson",
                        to="scheduling.lesson",
                    ),
                ),
                (
                    "lesson_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lessons",
                        to="scheduling.lessontype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LessonEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("makeup", "Make-up"),
                            ("guest", "Guest"),
                            ("administrative", "Administrative"),
                        ],
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="scheduling.lesson",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lesson_enrollments",
                        to="accounts.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LessonResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")], max_length=8
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responses",
                        to="scheduling.lesson",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lesson_responses",
                        to="accounts.student",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LessonRosterEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("group", "Group"),
                            ("enrollment", "Enrollment"),
                            ("manual", "Manual"),
                        ],
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deactivated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roster_entries",
                        to="scheduling.groupmembership",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roster_entries",
                        to="scheduling.lesson",
                    ),
                ),
                (
                    "lesson_enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roster_entries",
                        to="scheduling.lessonenrollment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lesson_roster_entries",
                        to="accounts.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("weekday", models.PositiveSmallIntegerField()),
                ("start_time", models.TimeField()),
                ("duration_minutes", models.PositiveSmallIntegerField()),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "minimum_attendees_override",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedule_templates",
                        to="accounts.coachprofile",
                    ),
                ),
                (
                    "lesson_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedule_templates",
                        to="scheduling.lessontype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="lesson",
            name="source_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generated_lessons",
                to="scheduling.scheduletemplate",
            ),
        ),
        migrations.CreateModel(
            name="TrainingGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "default_minimum_attendees",
                    models.PositiveSmallIntegerField(default=1),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["is_active", "name"],
                        name="training_group_active_name_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("default_minimum_attendees__gte", 1)),
                        name="training_group_minimum_gte_1",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="scheduletemplate",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="schedule_templates",
                to="scheduling.traininggroup",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lessons",
                to="scheduling.traininggroup",
            ),
        ),
        migrations.AddField(
            model_name="groupmembership",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to="scheduling.traininggroup",
            ),
        ),
        migrations.AddField(
            model_name="scheduletemplate",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="schedule_templates",
                to="scheduling.venue",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lessons",
                to="scheduling.venue",
            ),
        ),
        migrations.AddIndex(
            model_name="lessonenrollment",
            index=models.Index(
                fields=["lesson", "cancelled_at"], name="lesson_enroll_cancel_ix"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonenrollment",
            index=models.Index(
                fields=["student", "cancelled_at"], name="student_enroll_cancel_ix"
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonenrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cancelled_at__isnull", True)),
                fields=("lesson", "student"),
                name="lesson_enroll_active_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonenrollment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("cancelled_at__isnull", False),
                    ("cancelled_by__isnull", True),
                    _connector="OR",
                ),
                name="lesson_enroll_cancel_actor_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="lessonresponse",
            index=models.Index(
                fields=["lesson", "status"], name="lesson_response_status_ix"
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonresponse",
            constraint=models.UniqueConstraint(
                fields=("lesson", "student"), name="lesson_response_student_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonrosterentry",
            index=models.Index(
                fields=["lesson", "is_active"], name="lesson_roster_active_ix"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonrosterentry",
            index=models.Index(
                fields=["student", "is_active"], name="student_roster_active_ix"
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonrosterentry",
            constraint=models.UniqueConstraint(
                fields=("lesson", "student"), name="lesson_roster_student_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonrosterentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_active", True), ("deactivated_at__isnull", True)),
                    models.Q(("is_active", False), ("deactivated_at__isnull", False)),
                    _connector="OR",
                ),
                name="lesson_roster_active_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="groupmembership",
            index=models.Index(
                fields=["group", "starts_on", "ends_on"],
                name="membership_group_dates_ix",
            ),
        ),
        migrations.AddIndex(
            model_name="groupmembership",
            index=models.Index(
                fields=["student", "starts_on", "ends_on"],
                name="membership_student_dates_ix",
            ),
        ),
        migrations.AddConstraint(
            model_name="groupmembership",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ends_on__isnull", True),
                    ("ends_on__gte", models.F("starts_on")),
                    _connector="OR",
                ),
                name="group_membership_end_gte_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="groupmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ends_on__isnull", True)),
                fields=("student", "group"),
                name="group_membership_one_open_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="groupmembership",
            constraint=models.UniqueConstraint(
                fields=("student", "group", "starts_on"),
                name="membership_student_start_uq",
            ),
        ),
        migrations.AddIndex(
            model_name="scheduletemplate",
            index=models.Index(
                fields=["is_active", "weekday"], name="schedtpl_active_weekday_ix"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduletemplate",
            index=models.Index(
                fields=["group", "is_active"], name="schedtpl_group_active_ix"
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduletemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(("weekday__gte", 0), ("weekday__lte", 6)),
                name="schedule_template_weekday_0_6",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduletemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration_minutes__gt", 0)),
                name="schedtpl_duration_gt0",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduletemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_until__isnull", True),
                    ("valid_until__gte", models.F("valid_from")),
                    _connector="OR",
                ),
                name="schedtpl_until_gte_from",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduletemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("minimum_attendees_override__isnull", True),
                    ("minimum_attendees_override__gte", 1),
                    _connector="OR",
                ),
                name="schedtpl_minimum_gte1",
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["status", "starts_at"], name="lesson_status_start_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["group", "starts_at"], name="lesson_group_start_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["coach", "starts_at"], name="lesson_coach_start_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["status", "decision_deadline"],
                name="lesson_status_decision_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                name="lesson_ends_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("rsvp_deadline__lte", models.F("decision_deadline"))
                ),
                name="lesson_rsvp_before_decision",
            ),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.CheckConstraint(
                condition=models.Q(("decision_deadline__lte", models.F("starts_at"))),
                name="lesson_decision_before_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.CheckConstraint(
                condition=models.Q(("minimum_attendees__gte", 1)),
                name="lesson_minimum_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "cancelled"), _negated=True),
                    models.Q(
                        ("cancelled_at__isnull", False),
                        ("cancellation_reason__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="lesson_cancel_metadata_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("replacement_lesson__isnull", True),
                    ("status", "cancelled"),
                    _connector="OR",
                ),
                name="lesson_replace_cancelled_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_template__isnull", False)),
                fields=("source_template", "starts_at"),
                name="lesson_template_start_uniq",
            ),
        ),
    ]
