# Generated by Django 5.2 on 2026-10-01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="traininggroup",
            name="capacity",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="traininggroup",
            constraint=models.CheckConstraint(
                condition=models.Q(("capacity__isnull", True), ("capacity__gte", 1), _connector="OR"),
                name="training_group_capacity_gte_1",
            ),
        ),
        migrations.CreateModel(
            name="GroupSeatReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seat_reservations",
                        to="scheduling.traininggroup",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="group_seat_reservations",
                        to="accounts.student",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["group", "starts_on", "ends_on"],
                        name="seat_res_group_dates_ix",
                    ),
                    models.Index(
                        fields=["student", "starts_on", "ends_on"],
                        name="seat_res_student_dates_ix",
                    ),
                    models.Index(
                        fields=["group", "cancelled_at"],
                        name="seat_res_group_cancel_ix",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("ends_on__gte", models.F("starts_on"))),
                        name="seat_reservation_end_gte_start",
                    ),
                ],
            },
        ),
    ]
