# Generated by Django 5.2.17 on 2026-10-01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddConstraint(
            model_name="externalidentity",
            constraint=models.UniqueConstraint(
                fields=("user", "provider"),
                name="extid_user_provider_uq",
            ),
        ),
        migrations.CreateModel(
            name="AccountInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("student_access", "Student access"),
                            ("coach", "Coach"),
                        ],
                        max_length=24,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                (
                    "student_access_role",
                    models.CharField(
                        blank=True,
                        choices=[("self", "Self"), ("guardian", "Guardian")],
                        default="",
                        max_length=16,
                    ),
                ),
                (
                    "coach_display_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("account_display_name", models.CharField(max_length=100)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accepted_account_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_account_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revoked_account_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="account_invitations",
                        to="accounts.student",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["kind", "expires_at"],
                        name="account_invite_kind_exp_ix",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=(
                            (
                                models.Q(
                                    kind="student_access",
                                    student__isnull=False,
                                    student_access_role__in=["self", "guardian"],
                                    coach_display_name="",
                                )
                                | (
                                    models.Q(
                                        kind="coach",
                                        student__isnull=True,
                                        student_access_role="",
                                    )
                                    & ~models.Q(coach_display_name="")
                                )
                            )
                            & ~models.Q(account_display_name="")
                        ),
                        name="account_invite_target_ck",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                accepted_at__isnull=True,
                                accepted_by__isnull=True,
                            )
                            | models.Q(
                                accepted_at__isnull=False,
                                accepted_by__isnull=False,
                            )
                        ),
                        name="account_invite_accept_pair_ck",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                revoked_at__isnull=True,
                                revoked_by__isnull=True,
                            )
                            | models.Q(
                                revoked_at__isnull=False,
                                revoked_by__isnull=False,
                            )
                        ),
                        name="account_invite_revoke_pair_ck",
                    ),
                    models.CheckConstraint(
                        condition=~(
                            models.Q(accepted_at__isnull=False)
                            & models.Q(revoked_at__isnull=False)
                        ),
                        name="account_invite_terminal_ck",
                    ),
                ],
            },
        ),
    ]
