# Generated by Django 5.2.17 on 2026-09-23 10:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=80)),
                ("aggregate_type", models.CharField(max_length=64)),
                ("aggregate_id", models.UUIDField()),
                (
                    "correlation_id",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                ("payload", models.JSONField(default=dict)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["aggregate_type", "aggregate_id", "occurred_at"],
                        name="audit_aggregate_time_idx",
                    ),
                    models.Index(
                        fields=["event_type", "occurred_at"],
                        name="audit_event_time_idx",
                    ),
                    models.Index(
                        fields=["correlation_id"], name="audit_correlation_idx"
                    ),
                ],
            },
        ),
    ]
