# Generated by Django 5.2.17 on 2026-09-23 10:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("attendance", "0001_initial"),
        ("scheduling", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OneTimeEntitlement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entitlement_type",
                    models.CharField(
                        choices=[
                            ("single_ice", "Single ICE"),
                            ("single_hall", "Single HALL"),
                            ("individual_ice", "Individual ICE"),
                            ("mini_group_ice", "Mini-group ICE"),
                            ("trial_ice", "Trial ICE"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("ice", "ICE"), ("hall", "HALL")], max_length=16
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="one_time_entitlements",
                        to="scheduling.lesson",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="one_time_entitlements",
                        to="accounts.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("plan_code_snapshot", models.CharField(max_length=64)),
                ("plan_name_snapshot", models.CharField(max_length=128)),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="accounts.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubscriptionAllowance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("ice", "ICE"), ("hall", "HALL")], max_length=16
                    ),
                ),
                ("visit_limit_snapshot", models.PositiveSmallIntegerField()),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allowances",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MakeupEntitlement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("ice", "ICE"), ("hall", "HALL")], max_length=16
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("medical", "Verified medical absence"),
                            ("school_reschedule", "School reschedule"),
                            ("administrative", "Administrative"),
                        ],
                        max_length=24,
                    ),
                ),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_justification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="makeup_entitlements",
                        to="attendance.absencejustification",
                    ),
                ),
                (
                    "source_lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generated_makeup_entitlements",
                        to="scheduling.lesson",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="makeup_entitlements",
                        to="accounts.student",
                    ),
                ),
                (
                    "target_lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="targeted_makeup_entitlements",
                        to="scheduling.lesson",
                    ),
                ),
                (
                    "source_subscription_allowance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="makeup_entitlements",
                        to="subscriptions.subscriptionallowance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttendanceCoverage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coverages",
                        to="attendance.attendance",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reversed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "makeup_entitlement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coverages",
                        to="subscriptions.makeupentitlement",
                    ),
                ),
                (
                    "one_time_entitlement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coverages",
                        to="subscriptions.onetimeentitlement",
                    ),
                ),
                (
                    "subscription_allowance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coverages",
                        to="subscriptions.subscriptionallowance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubscriptionLedgerEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("grant", "Grant"),
                            ("consume", "Consume"),
                            ("restore", "Restore"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=16,
                    ),
                ),
                ("delta", models.SmallIntegerField()),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "allowance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="subscriptions.subscriptionallowance",
                    ),
                ),
                (
                    "coverage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="subscriptions.attendancecoverage",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("validity_months", models.PositiveSmallIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["is_active", "name"], name="subplan_active_name_ix"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("validity_months", 1)),
                        name="subscription_plan_one_month",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="subscriptions.subscriptionplan",
            ),
        ),
        migrations.CreateModel(
            name="SubscriptionPlanAllowance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("ice", "ICE"), ("hall", "HALL")], max_length=16
                    ),
                ),
                ("visit_limit", models.PositiveSmallIntegerField()),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowances",
                        to="subscriptions.subscriptionplan",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="onetimeentitlement",
            index=models.Index(
                fields=["student", "lesson", "category"],
                name="onetime_lesson_lookup_ix",
            ),
        ),
        migrations.AddIndex(
            model_name="onetimeentitlement",
            index=models.Index(
                fields=["lesson", "cancelled_at"], name="onetime_active_ix"
            ),
        ),
        migrations.AddConstraint(
            model_name="onetimeentitlement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("category", "ice"), ("entitlement_type", "single_ice")),
                    models.Q(("category", "hall"), ("entitlement_type", "single_hall")),
                    models.Q(
                        ("category", "ice"), ("entitlement_type", "individual_ice")
                    ),
                    models.Q(
                        ("category", "ice"), ("entitlement_type", "mini_group_ice")
                    ),
                    models.Q(("category", "ice"), ("entitlement_type", "trial_ice")),
                    _connector="OR",
                ),
                name="onetime_type_category_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="onetimeentitlement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("cancelled_at__isnull", False),
                    ("cancelled_by__isnull", True),
                    _connector="OR",
                ),
                name="onetime_cancel_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionallowance",
            index=models.Index(
                fields=["subscription", "category"], name="suballow_lookup_ix"
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionallowance",
            constraint=models.UniqueConstraint(
                fields=("subscription", "category"), name="suballow_category_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionallowance",
            constraint=models.CheckConstraint(
                condition=models.Q(("visit_limit_snapshot__gt", 0)),
                name="suballow_limit_gt0",
            ),
        ),
        migrations.AddIndex(
            model_name="makeupentitlement",
            index=models.Index(
                condition=models.Q(("cancelled_at__isnull", True)),
                fields=["student", "category", "valid_until"],
                name="makeup_available_ix",
            ),
        ),
        migrations.AddConstraint(
            model_name="makeupentitlement",
            constraint=models.CheckConstraint(
                condition=models.Q(("valid_until__gte", models.F("valid_from"))),
                name="makeup_until_gte_from",
            ),
        ),
        migrations.AddConstraint(
            model_name="makeupentitlement",
            constraint=models.UniqueConstraint(
                fields=("student", "source_lesson", "reason"),
                name="makeup_student_lesson_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="makeupentitlement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("reason", "medical"), _negated=True),
                    ("source_justification__isnull", False),
                    _connector="OR",
                ),
                name="makeup_medical_justif_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="makeupentitlement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("reason", "school_reschedule"), _negated=True),
                    ("target_lesson__isnull", False),
                    _connector="OR",
                ),
                name="makeup_resched_target_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="makeupentitlement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("cancelled_at__isnull", False),
                    ("cancelled_by__isnull", True),
                    _connector="OR",
                ),
                name="makeup_cancel_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancecoverage",
            index=models.Index(
                fields=["subscription_allowance", "reversed_at"],
                name="coverage_allowance_reverse_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancecoverage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reversed_at__isnull", True)),
                fields=("attendance",),
                name="coverage_attendance_active_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancecoverage",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("one_time_entitlement__isnull", False),
                    ("reversed_at__isnull", True),
                ),
                fields=("one_time_entitlement",),
                name="coverage_onetime_active_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancecoverage",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("makeup_entitlement__isnull", False), ("reversed_at__isnull", True)
                ),
                fields=("makeup_entitlement",),
                name="coverage_one_active_per_makeup",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancecoverage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("one_time_entitlement__isnull", True),
                        ("subscription_allowance__isnull", False),
                    ),
                    models.Q(
                        ("one_time_entitlement__isnull", False),
                        ("subscription_allowance__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="coverage_primary_source_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancecoverage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("makeup_entitlement__isnull", True),
                    ("subscription_allowance__isnull", False),
                    _connector="OR",
                ),
                name="coverage_makeup_allow_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancecoverage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reversed_at__isnull", False),
                    ("reversed_by__isnull", True),
                    _connector="OR",
                ),
                name="coverage_reverse_consistency",
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionledgerentry",
            index=models.Index(
                fields=["allowance", "created_at"], name="ledger_allowance_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionledgerentry",
            index=models.Index(
                fields=["allowance", "entry_type"], name="ledger_allowance_type_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("delta__gt", 0), ("entry_type", "grant")),
                    models.Q(("delta", -1), ("entry_type", "consume")),
                    models.Q(("delta", 1), ("entry_type", "restore")),
                    models.Q(
                        ("entry_type", "adjustment"),
                        models.Q(("delta", 0), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="ledger_delta_matches_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("entry_type__in", ["consume", "restore"]),
                        ("coverage__isnull", False),
                    ),
                    models.Q(
                        ("entry_type__in", ["grant", "adjustment"]),
                        ("coverage__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="ledger_coverage_requirement",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionledgerentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("entry_type", "grant")),
                fields=("allowance",),
                name="ledger_one_grant_per_allowance",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionledgerentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("coverage__isnull", False)),
                fields=("coverage", "entry_type"),
                name="ledger_coverage_type_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["student", "valid_from", "valid_until"],
                name="subscription_student_dates_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["student", "-valid_from"], name="subscription_history_ix"
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                condition=models.Q(("valid_until__gte", models.F("valid_from"))),
                name="subscription_until_gte_from",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("cancelled_at__isnull", False),
                    ("cancelled_by__isnull", True),
                    _connector="OR",
                ),
                name="subscription_cancel_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionplanallowance",
            index=models.Index(
                fields=["category", "visit_limit"], name="subplan_allow_lookup_ix"
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionplanallowance",
            constraint=models.UniqueConstraint(
                fields=("plan", "category"), name="subplan_allow_category_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionplanallowance",
            constraint=models.CheckConstraint(
                condition=models.Q(("visit_limit__gt", 0)),
                name="subplan_allow_limit_gt0",
            ),
        ),
    ]
