# Generated by Django 5.2 on 2026-10-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0002_group_capacity_seat_reservation"),
        ("subscriptions", "0005_pending_subscription_dates"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupplacehold",
            name="seat_reservation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="place_hold",
                to="scheduling.groupseatreservation",
            ),
        ),
    ]
