# Generated by Django 5.2 on 2026-10-01

import django.db.models.deletion
from datetime import datetime, time, timedelta
from zoneinfo import ZoneInfo

from django.conf import settings
from django.db import migrations, models


def backfill_active_place_hold_reservations(apps, schema_editor):
    GroupPlaceHold = apps.get_model("subscriptions", "GroupPlaceHold")
    GroupSeatReservation = apps.get_model("scheduling", "GroupSeatReservation")
    LessonEnrollment = apps.get_model("scheduling", "LessonEnrollment")
    LessonRosterEntry = apps.get_model("scheduling", "LessonRosterEntry")
    school_tz = ZoneInfo(settings.SCHOOL_TIME_ZONE)

    for hold in GroupPlaceHold.objects.filter(
        status="active",
        seat_reservation__isnull=True,
    ).iterator():
        reservation = GroupSeatReservation.objects.create(
            student_id=hold.student_id,
            group_id=hold.group_id,
            starts_on=hold.period_from,
            ends_on=hold.period_until,
            created_by_id=hold.created_by_id,
        )
        hold.seat_reservation_id = reservation.id
        hold.save(update_fields=["seat_reservation"])

        starts_at = datetime.combine(
            hold.period_from,
            time.min,
            tzinfo=school_tz,
        )
        ends_at = datetime.combine(
            hold.period_until + timedelta(days=1),
            time.min,
            tzinfo=school_tz,
        )
        explicit_lesson_ids = LessonEnrollment.objects.filter(
            student_id=hold.student_id,
            cancelled_at__isnull=True,
            lesson__group_id=hold.group_id,
            lesson__starts_at__gte=starts_at,
            lesson__starts_at__lt=ends_at,
        ).values_list("lesson_id", flat=True)
        (
            LessonRosterEntry.objects.filter(
                student_id=hold.student_id,
                lesson__group_id=hold.group_id,
                lesson__starts_at__gte=starts_at,
                lesson__starts_at__lt=ends_at,
                lesson__status__in=["rsvp_open", "confirmed"],
                source="group",
                is_active=True,
            )
            .exclude(lesson_id__in=explicit_lesson_ids)
            .update(
                is_active=False,
                deactivated_at=hold.fee_confirmed_at,
                deactivated_by_id=hold.fee_confirmed_by_id,
            )
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0002_group_capacity_seat_reservation"),
        ("subscriptions", "0005_pending_subscription_dates"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupplacehold",
            name="seat_reservation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="place_hold",
                to="scheduling.groupseatreservation",
            ),
        ),
        migrations.RunPython(
            backfill_active_place_hold_reservations,
            noop_reverse,
        ),
        migrations.AddConstraint(
            model_name="groupplacehold",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "active"),
                    _negated=True,
                )
                | models.Q(("seat_reservation__isnull", False)),
                name="grouphold_active_has_seat_ck",
            ),
        ),
    ]
