# Generated by Django 5.2 on 2026-10-01

import django.db.models.deletion
from datetime import timedelta

from django.db import migrations, models


def backfill_active_place_hold_reservations(apps, schema_editor):
    GroupPlaceHold = apps.get_model("subscriptions", "GroupPlaceHold")
    GroupSeatReservation = apps.get_model("scheduling", "GroupSeatReservation")
    for hold in GroupPlaceHold.objects.filter(
        status="active",
        seat_reservation__isnull=True,
    ).iterator():
        reservation = GroupSeatReservation.objects.create(
            student_id=hold.student_id,
            group_id=hold.group_id,
            starts_on=hold.period_from,
            ends_on=hold.period_until + timedelta(days=1),
            created_by_id=hold.created_by_id,
        )
        hold.seat_reservation_id = reservation.id
        hold.save(update_fields=["seat_reservation"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0002_group_capacity_seat_reservation"),
        ("subscriptions", "0005_pending_subscription_dates"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupplacehold",
            name="seat_reservation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="place_hold",
                to="scheduling.groupseatreservation",
            ),
        ),
        migrations.RunPython(
            backfill_active_place_hold_reservations,
            noop_reverse,
        ),
    ]
