# Generated by Django 5.2.17 on 2026-09-23 10:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("scheduling", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AbsenceJustification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("medical", "Medical")],
                        default="medical",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "verification_method",
                    models.CharField(
                        choices=[("in_person", "In person")],
                        default="in_person",
                        max_length=16,
                    ),
                ),
                (
                    "declared_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "declared_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="absence_justifications",
                        to="scheduling.lesson",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="absence_justifications",
                        to="accounts.student",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "declared_at"],
                        name="absence_status_declared_ix",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "lesson", "type"),
                        name="absence_student_lesson_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("reviewed_at__isnull", True),
                                ("revoked_at__isnull", True),
                                ("status", "pending"),
                            ),
                            models.Q(
                                ("reviewed_at__isnull", False),
                                ("revoked_at__isnull", True),
                                ("status", "verified"),
                            ),
                            models.Q(
                                ("reviewed_at__isnull", False),
                                ("revoked_at__isnull", True),
                                ("status", "rejected"),
                            ),
                            models.Q(
                                ("reviewed_at__isnull", False),
                                ("revoked_at__isnull", False),
                                ("status", "revoked"),
                            ),
                            _connector="OR",
                        ),
                        name="absence_state_metadata_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("present", "Present"), ("absent", "Absent")],
                        max_length=16,
                    ),
                ),
                ("marked_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_records",
                        to="scheduling.lesson",
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_records",
                        to="accounts.student",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["lesson", "status"], name="attendance_lesson_status_idx"
                    ),
                    models.Index(
                        fields=["student", "marked_at"],
                        name="attendance_student_marked_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("lesson", "student"),
                        name="attendance_lesson_student_uniq",
                    )
                ],
            },
        ),
    ]
